context:
  name: dooit
  version: "3.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5ac238f2d781c438eabc5616428697c7e0905130e80d3b814126f64a925d0c70

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      - dooit = dooit.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - pyyaml >=6.0.2
    - tzlocal >=5.2
    - textual >=3.2
    - python-dateutil >=2.9.0.post0
    - sqlalchemy >=2.0.36
    - platformdirs >=4.3.6
    - click >=8.1.7
    - pyperclip >=1.9.0

tests:
  - python:
      imports:
        - dooit
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - dooit --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  repository: https://github.com/dooit-org/dooit
  summary: 'An awesome TUI todo manager'
  description: |
    Dooit is a TUI todo manager aimed to be highly customizable!
    It's built with Textual
    Thank you for trying out dooit! I hope you enjoy it.
    Feel free to open any feature requests if you have great ideas
  license: MIT
  license_file: LICENSE
  homepage: https://dooit-org.github.io/dooit/

extra:
  recipe-maintainers:
    - kraanzu
    - claudiushaag
